### ISSUE TITLE
FFmpeg Noise Binary Sensor: stops working

### ISSUE THREAD

**Issue by Molodax** [pvizeli/ha-ffmpeg#13]
Dear @pvizeli,

May I kindly ask you to look at the issue https://github.com/home-assistant/home-assistant/issues/7081?
The problem is that the sensor worked seamlessly before the binary sensor has been split to motion and noise ones.
Also regular restarting of ffmpeg, to fix the problem, is triggering the sensor itself, therefore, this workaround is far from optimal too.

**Comment by pvizeli** [comment]
Fix with https://github.com/pvizeli/ha-ffmpeg/pull/14
