### ISSUE TITLE
ERROR:haffmpeg.core:FFmpeg isn't running!

### ISSUE THREAD

**Issue by wiktor-grochal** [pvizeli/ha-ffmpeg#2]
Not sure if its an issue or just me misconfigurating

 i can't figure out how to get ha-ffmpeg to work. I builded it succesfuly on rpi2b and my config is as follows
```
    camera:
     - platform: ffmpeg
        input: rtsp://admin:admin@192.168.1.170/stream2
        name: FFmpeg
        ffmpeg_bin: /usr/local/bin/ffmpeg
        extra_arguments: -rtsp_transport tcp -analyzeduration 15
```
I tested it using this command and it works just fine.
```
ffmpeg -rtsp_transport tcp -analyzeduration 15 -i rtsp://admin:admin@192.168.1.170/stream2 -an -f null -
```
Althoght it some times give an error like this:
```
[null @ 0x2f57b10] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 6174 >= 6174
    Last message repeated 1 times
```
On my ha log i see following messages
```
INFO:homeassistant.loader:Loaded camera.ffmpeg from homeassistant.components.camera.ffmpeg
INFO:homeassistant.core:Bus:Handling <Event state_changed[L]: new_state=<state camera.ffmpeg=idle; entity_picture=/api/camera_proxy/camera.ffmpeg?to                                                                                         ken=1894426928, friendly_name=FFmpeg, access_token=1894426928 @ 2016-09-06T05:24:19.531882+02:00>, entity_id=camera.ffmpeg, old_state=None>
INFO:homeassistant.core:Bus:Handling <Event component_loaded[L]: component=camera>

INFO:homeassistant.components.http:Serving /api/camera_proxy/camera.ffmpeg to 192.168.1.188 (auth: True)
ERROR:haffmpeg.core:FFmpeg isn't running!
```

**Comment by pvizeli** [comment]
Try this:
 ```
camera:
     - platform: ffmpeg
        input: -rtsp_transport tcp -i rtsp://admin:admin@192.168.1.170/stream2
        name: FFmpeg
        ffmpeg_bin: /usr/local/bin/ffmpeg
```

The `-analyzeduration 15` means that ffmpeg have 15 macro seconds time to analyse all data and that is to short. Default is 5'000'000 (5 seconds). I think you don't need this option or with value greater than the default value.

**Comment by wiktor-grochal** [comment]
:+1:  it worked :)) at least kind of :P  its laggy and the miniature is not always showing and takes really long time to show up and wideo on preview is like in slow motion. Anything i can try to fix that?

**Comment by wiktor-grochal** [comment]
Thats deffinitly a performance issue setting -threads 4 helped a little bit but its still unusable

**Comment by pvizeli** [comment]
Do you have try a lossless Option with `extra_arguments`? I'm working an a update for image capture with ffmpeg instead HA. The preview is update only all 10 seconds by HA. The start of Video can improve with a smaller buffer (at work for next update). Do you have a small camera Image? FFmpeg use autodetect for threads an use this as core.

**Comment by wiktor-grochal** [comment]
lossless seemed to make it better, although the best results gives the -q:v 2 option. One thing to notice is that it works fine for a given time and then stops and the image freezes on a certain point in time. Needs to restart whole page for it to retriger. The video also has about 10 s lag, kind of defeats the purpose of having the live preview of who is standing at your door. 
Suming up the streaming is ok with -q:v 2 option although it has lag and stops after about 20 seconds and need page refresh to unfreeze.

**Comment by pvizeli** [comment]
That is not a ffmpeg bug. All cameras on HA work at the Moment with this Problem. I hope a update of cherrpy, Werkzeug or HA core change to async should solve that.

**Comment by efp1** [comment]
Thanks guys! This thread helped solved the issue I had! (pretty much the same issue here).
