### ISSUE TITLE
Support for H.264 streams?

### ISSUE THREAD

**Issue by vladm** [pvizeli/ha-ffmpeg#8]
Hello,

is it possible to alter ffmpeg options to generate H264 stream instead of MJPEG? I.e. use libx264 codec?

**Comment by pvizeli** [comment]
Hi,

HA only support mjpeg streams in UI. That is the reason why I do that in this way.

**Comment by iwoloschin** [comment]
Is the limitation of mjpeg only streams an actual technology limitation, or just a matter of no one having bothered doing the work yet?
